[package]
name = "ironwood-target-codegen"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace]
resolver = "3"

[lib]
crate-type = ["rlib"]

[dependencies]
ironwood-approval = { path = "../../crates/approval", default-features = false }
orchard = { version = "=0.15.3", default-features = false }
rand_chacha = { version = "=0.3.1", default-features = false }

[profile.release]
opt-level = 3
codegen-units = 1
lto = false
panic = "abort"
